# Generated by Django 5.2.7 on 2025-10-03 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('user_prompt', models.TextField(verbose_name='用户提示词')),
                ('system_prompt', models.TextField(verbose_name='系统提示词')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128, verbose_name='产品')),
                ('core_job', models.CharField(max_length=128, verbose_name='核心任务')),
                ('job_map', models.CharField(max_length=512, verbose_name='任务地图')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='子流程')),
                ('index', models.IntegerField(verbose_name='流程序号')),
            ],
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='输入变量名称')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.agents')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppo', models.CharField(max_length=128, verbose_name='机会描述')),
                ('type', models.SmallIntegerField(choices=[(1, 'related_job'), (2, 'desired_outcome'), (3, 'constrain')], verbose_name='机会类型')),
                ('customer', models.CharField(max_length=128, verbose_name='目标客户')),
                ('solution', models.CharField(max_length=512, verbose_name='针对性方案')),
                ('slogan', models.CharField(max_length=128, verbose_name='宣传口号')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.cases')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='步骤序号')),
                ('run', models.CharField(max_length=32, verbose_name='执行函数')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.agents')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.workflows')),
            ],
        ),
        migrations.CreateModel(
            name='Contexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='变量名称')),
                ('content', models.TextField(verbose_name='变量内容')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.workflows')),
            ],
        ),
    ]
