# Generated by Django 5.2.7 on 2025-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='description',
            field=models.CharField(default='系统管理员', max_length=64, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
