# Generated by Django 5.2.7 on 2025-10-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_agents_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkFlows',
            new_name='Flows',
        ),
        migrations.RenameField(
            model_name='contexts',
            old_name='workflow',
            new_name='flow',
        ),
        migrations.RenameField(
            model_name='steps',
            old_name='workflow',
            new_name='flow',
        ),
        migrations.AddField(
            model_name='contexts',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.cases'),
            preserve_default=False,
        ),
    ]
