# Generated by Django 5.2.7 on 2025-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_rename_workflows_flows_rename_workflow_contexts_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flows',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
