# Generated by Django 5.2.7 on 2025-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_flows_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='output',
            field=models.CharField(default='core_job', max_length=32, verbose_name='输出变量'),
            preserve_default=False,
        ),
    ]
