# Generated by Django 5.2.7 on 2025-10-11 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_agents_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contexts',
            name='name',
        ),
        migrations.AddField(
            model_name='flows',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app01.flows', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='contexts',
            name='content',
            field=models.TextField(verbose_name='上下文'),
        ),
    ]
