# Generated by Django 5.2.7 on 2025-10-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_remove_contexts_name_flows_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='info',
            field=models.TextField(default=' ', verbose_name='产品说明'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cases',
            name='core_job',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='核心任务'),
        ),
        migrations.AlterField(
            model_name='cases',
            name='job_map',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='任务地图'),
        ),
    ]
