# Generated by Django 5.2.7 on 2025-10-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_cases_info_alter_cases_core_job_alter_cases_job_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps',
            name='run',
        ),
    ]
