# Generated by Django 5.2.7 on 2025-10-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_agenttimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttimer',
            name='case',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='app01.cases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cases',
            name='delta',
            field=models.FloatField(blank=True, null=True, verbose_name='用时（秒）'),
        ),
        migrations.AddField(
            model_name='cases',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='cases',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
