# Generated by Django 5.2.7 on 2025-10-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_agenttimer_case_cases_delta_cases_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('delta', models.FloatField(verbose_name='用时（秒）')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.cases')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.steps')),
            ],
        ),
        migrations.DeleteModel(
            name='AgentTimer',
        ),
    ]
