# Generated by Django 5.2.7 on 2025-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_steptimer_delete_agenttimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='<UNK>')),
                ('password', models.CharField(max_length=64, verbose_name='<UNK>')),
            ],
        ),
    ]
