# Generated by Django 5.2.7 on 2025-11-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_cases_user_alter_users_password_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='user',
        ),
    ]
