# Generated by Django 5.2.7 on 2025-11-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_cases_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.users'),
        ),
    ]
