# Generated by Django 5.2.7 on 2025-11-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_alter_cases_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='user',
        ),
    ]
