# Generated by Django 5.2.7 on 2025-11-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_cases_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='完成'),
        ),
    ]
