# Generated by Django 5.2.7 on 2025-12-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_cases_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
