# Generated by Django 5.2.7 on 2025-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_cases_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='pinned_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='置顶时间'),
        ),
    ]
